resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml
  - integration-config.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
labels:
  - pairs:
      app.kubernetes.io/name: creator-store-api
