drop table if exists sessions;
drop table if exists notification_preferences;
drop table if exists stores;
drop table if exists creators;

create table creators (
  id bigint generated by default as identity primary key,
  handle varchar(40) unique not null,
  display_name varchar(80) not null,
  email varchar(255) unique not null,
  phone varchar(32),
  password_hash varchar(255) not null,
  bio varchar(280) not null default '',
  avatar_url varchar(2048),
  created_at timestamp with time zone not null default current_timestamp
);

create table stores (
  id bigint generated by default as identity primary key,
  creator_id bigint unique not null references creators(id) on delete cascade,
  title varchar(100) not null,
  currency char(3) not null default 'INR',
  published boolean not null default true,
  payouts_enabled boolean not null default false
);

create table notification_preferences (
  creator_id bigint primary key references creators(id) on delete cascade,
  order_emails boolean not null default true,
  marketing_emails boolean not null default true,
  payout_emails boolean not null default true
);

create table sessions (
  id varchar(64) primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  created_at timestamp with time zone not null default current_timestamp,
  expires_at timestamp with time zone not null,
  revoked_at timestamp with time zone
);
