drop table if exists sessions;
drop table if exists notification_preferences;
drop table if exists products;
drop table if exists links;
drop table if exists stores;
drop table if exists creators;

create table creators (
  id bigint generated by default as identity primary key,
  handle varchar(40) unique not null,
  display_name varchar(80) not null,
  email varchar(255) unique not null,
  phone varchar(32),
  password_hash varchar(255) not null,
  bio varchar(280) not null default '',
  avatar_url varchar(2048),
  created_at timestamp with time zone not null default current_timestamp
);

create table stores (
  id bigint generated by default as identity primary key,
  creator_id bigint unique not null references creators(id) on delete cascade,
  title varchar(100) not null,
  currency char(3) not null default 'INR',
  published boolean not null default true,
  payouts_enabled boolean not null default false
);

alter table stores add column tagline varchar(180) not null default 'Systems and templates for independent creators.';
alter table stores add column theme varchar(40) not null default 'violet';
alter table stores add column accent_color varchar(7) not null default '#6842d7';
alter table stores add column background_style varchar(30) not null default 'soft-gradient';
alter table stores add column button_style varchar(20) not null default 'rounded';
alter table stores add column font_style varchar(20) not null default 'modern';
alter table stores add column show_products boolean not null default true;
alter table stores add column show_links boolean not null default true;

create table links (
  id bigint generated by default as identity primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  title varchar(100) not null,
  url varchar(2048) not null,
  description varchar(500) not null default '',
  brand_name varchar(100) not null default '',
  thumbnail_url varchar(2048),
  call_to_action varchar(60) not null default 'Visit link',
  coupon_code varchar(80) not null default '',
  offer_text varchar(120) not null default '',
  disclosure varchar(160) not null default '',
  position integer not null default 0,
  pinned boolean not null default false,
  published boolean not null default true,
  starts_at timestamp with time zone,
  ends_at timestamp with time zone
);

create table products (
  id bigint generated by default as identity primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  type varchar(40) not null default 'digital-download',
  title varchar(100) not null,
  subtitle varchar(160) not null default '',
  call_to_action varchar(60) not null default 'Get access',
  thumbnail_style varchar(20) not null default 'preview',
  description varchar(2000) not null,
  price_cents integer not null default 0,
  thumbnail_url varchar(2048),
  pinned boolean not null default false,
  position integer not null default 0,
  configuration_json varchar(10000) not null default '{}',
  status varchar(20) not null default 'published'
);

create table notification_preferences (
  creator_id bigint primary key references creators(id) on delete cascade,
  order_emails boolean not null default true,
  marketing_emails boolean not null default true,
  payout_emails boolean not null default true
);

create table sessions (
  id varchar(64) primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  created_at timestamp with time zone not null default current_timestamp,
  expires_at timestamp with time zone not null,
  revoked_at timestamp with time zone
);
