drop table if exists leads;
drop table if exists store_visits;
drop table if exists products;
drop table if exists stores;
drop table if exists creators;

create table creators (
  id bigint generated by default as identity primary key,
  handle varchar(40) unique not null,
  display_name varchar(80) not null,
  email varchar(255) unique not null,
  password_hash varchar(255) not null,
  bio varchar(280) not null default ''
);

create table stores (
  id bigint generated by default as identity primary key,
  creator_id bigint unique not null references creators(id) on delete cascade,
  title varchar(100) not null,
  currency char(3) not null default 'INR',
  published boolean not null default true
);

create table products (
  id bigint generated by default as identity primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  type varchar(40) not null,
  title varchar(100) not null,
  description varchar(2000) not null,
  price_cents integer not null default 0,
  status varchar(20) not null default 'published',
  configuration_json text not null default '{}'
);

create table leads (
  id bigint generated by default as identity primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  email varchar(255) not null,
  name varchar(120),
  phone varchar(32),
  consent_given boolean not null default false,
  consent_text varchar(500),
  idempotency_key varchar(120),
  request_fingerprint varchar(64),
  created_at timestamp with time zone not null default current_timestamp,
  unique(product_id,idempotency_key)
);

create table store_visits (
  id bigint generated by default as identity primary key,
  creator_id bigint not null references creators(id) on delete cascade,
  path varchar(512) not null,
  referrer varchar(512),
  occurred_at timestamp with time zone not null default current_timestamp
);

insert into creators(id,handle,display_name,email,password_hash)
values(10,'lead_creator','Lead Creator','lead@example.test','disabled');
insert into creators(id,handle,display_name,email,password_hash)
values(20,'other_creator','Other Creator','other@example.test','disabled');
insert into stores(creator_id,title,published) values(10,'Lead Store',true);
insert into stores(creator_id,title,published) values(20,'Other Store',true);
insert into products(id,creator_id,type,title,description,status,configuration_json)
values(100,10,'lead-magnet','Private guide','A guide','published',
  '{"schemaVersion":1,"deliveryMode":"redirect","redirectUrl":"https://private.example/guide","collectName":true,"collectEmail":true,"collectPhone":true,"consentText":"Send me this guide."}');
insert into products(id,creator_id,type,title,description,status,configuration_json)
values(101,10,'digital-download','Paid guide','A paid guide','published','{}');
